version: '3'
services:
  postgres:
    image: 'postgres:latest'
    restart: always
    container_name: 'complexapp-postgres'
  redis:
    image: 'redis:latest'
    restart: always
    container_name: 'complexapp-redis'
  nginx:
    container_name: 'complexapp-nginx'
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    container_name: 'complexapp-server'
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    depends_on: 
      - postgres
      - redis
  client:
    container_name: 'complexapp-client'
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    restart: always
    volumes:
      - /app/node_modules
      - ./client:/app
    depends_on: 
      - postgres
      - redis
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    restart: always
    container_name: 'complexapp-worker'
    volumes:
      - /app/node_modules
      - ./worker:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
networks:
  complex-app-network: